# netlify.toml

[build]
  # Tell Netlify to publish from the repository root
  publish = "."

# Proxy every path to your Shopify store
[[redirects]]
  from       = "/*"
  to         = "https://venusng.shop/:splat"
  status     = 200
  force      = true
  forwardQuery = true
